##### Departamento de Física - Faculdade de Ciências e Tecnologia da Universidade de Coimbra #####
# Física Computacional - Ficha 6 - Diagonalização de Matrizes #
### Rafael Isaque Santos - 2012144694 - Licenciatura em Física ###

In [78]:
import numpy as np
import numpy.linalg
import matplotlib.pyplot as pl
%matplotlib inline

In [131]:
def npower(matrix, k):          # método da potência n-ésima para um
    x = np.array([1, 0, 0])
    print(0, x, x.transpose().dot(matrix).dot(x))
    for i in range(k):
        x = matrix.dot(x)
        x_norm = linalg.norm(x)
        xk = x / x_norm
        eig = xk.transpose().dot(A).dot(xk)
        print(i+1, xk, eig)
    return xk, eig

In [133]:
def npower_eps(matrix, lambda_diff):
    x0 = np.array([1, 0, 0])
    xk = matrix.dot(x)
    xk = xk / linalg.norm(xk)
    k = 1
    def eig(vector): return vector.transpose().dot(matrix).dot(vector)
    print(k, eig(xk))
    while np.abs(eig(xk) - eig(x0)) > lambda_diff:
        x0 = xk
        xk = matrix.dot(xk)
        xk = xk / linalg.norm(xk)
        k += 1
        if k%2 != 0: print(k, eig(xk))
    return k, eig(xk), xk, eig(x0), x0, np.abs(eig(x0) - eig(xk))

#### Estimativa de $\lambda$ em cada iteração ímpar: ####
Abaixo, número de iterações necessárias, valor próprio encontrado ao final, vector próprio associado, valor próprio do passo anterior e seu vector próprio, e diferença entre último e penúltimo vectores próprios encontrados.

In [134]:
npower_eps(A, 1e-5)

(12,
 2.5365240675056864,
 array([ 0.53206175,  0.46220525,  0.7094199 ]),
 2.5365205948964937,
 array([ 0.53247398,  0.46272715,  0.70877009]),
 3.4726091926451375e-06)

1 2.33333333333
3 2.50816648772
5 2.5331579533
7 2.5361342826
9 2.53648044612
11 2.5365205949


**Cálculo utilizando o método sem critério de parada, mas em vez disso, em função do k**
Retornando:
+ Iteração
+ Vector Normalizado
+ Valor próprio

In [132]:
npower(A, 6)

(array([ 0.54584763,  0.47976191,  0.6869344 ]), 2.5353766745109372)

0 [1 0 0] 1.0
1 [ 0.66666667  0.66666667  0.33333333] 2.33333333333
2 [ 0.6328463   0.59768817  0.49221379] 2.45735475896
3 [ 0.59709395  0.54733612  0.58643156] 2.50816648772
4 [ 0.57186238  0.51354514  0.63972244] 2.52669547532
5 [ 0.55572103  0.49247561  0.66980737] 2.5331579533
6 [ 0.54584763  0.47976191  0.6869344 ] 2.53537667451


In [39]:
A = np.array([[1., 1, 1/2], [1, 1, 1/4], [1/2, 1/4, 2]])

In [110]:
npower(A, 12)

(array([ 0.53206175,  0.46220525,  0.7094199 ]), 2.5365240675056864)

1 2.33333333333 [ 0.66666667  0.66666667  0.33333333]
2 2.45735475896 [ 0.6328463   0.59768817  0.49221379]
3 2.50816648772 [ 0.59709395  0.54733612  0.58643156]
4 2.52669547532 [ 0.57186238  0.51354514  0.63972244]
5 2.5331579533 [ 0.55572103  0.49247561  0.66980737]
6 2.53537667451 [ 0.54584763  0.47976191  0.6869344 ]
7 2.5361342826 [ 0.53993856  0.47221     0.69676687]
8 2.53639249588 [ 0.53644173  0.46775999  0.70244634]
9 2.53648044612 [ 0.53438498  0.46514898  0.70574012]
10 2.53651039645 [ 0.53317934  0.46362061  0.70765509]
11 2.5365205949 [ 0.53247398  0.46272715  0.70877009]
12 2.53652406751 [ 0.53206175  0.46220525  0.7094199 ]


# Cálculo de Valores e Vectores Próprios utilizando uma função interna do __numpy__

In [109]:
np.linalg.eig(A)

(array([-0.01664728,  2.53652586,  1.48012142]),
 array([[ 0.72120713, -0.53148341, -0.44428106],
        [-0.68634929, -0.46147335, -0.56210942],
        [-0.09372796, -0.71032931,  0.69760113]]))